---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: s2i-nodejs-build
spec:
  source:
    type: Git
    git:
      url: https://github.com/redhat-openshift-builds/samples
    contextDir: s2i-build/nodejs
  strategy:
    name: source-to-image
    kind: ClusterBuildStrategy
  paramValues:
  - name: builder-image
    value: quay.io/centos7/nodejs-12-centos7:master
  output:
    image: quay.io/syedriko/s2i-nodejs-example
    pushSecret: quay-syedriko-secret
