#!/bin/bash

# Split lockfiles for Konflux Cachi2 prefetch (PyPI source vs RHOAI wheels) from pyproject.toml.
# - Compile with uv (dual index + overrides), like openshift/lightspeed-service
# - Emit:
#   - requirements.hashes.source.<flavor>.txt, requirements.hashes.wheel.<flavor>.txt
#   - requirements-build.<flavor>.txt
#   - update binary package lists in the matching .tekton PipelineRuns
#
# Flavors: cpu (cpu-ubi9 RHOAI index) and gpu (cuda12.9-ubi9 RHOAI index).
# Usage: ./scripts/konflux_requirements.sh [cpu|gpu]

set -euo pipefail

FLAVOR="${1:-}"
if [[ "$FLAVOR" != "cpu" && "$FLAVOR" != "gpu" ]]; then
	echo "Usage: $0 {cpu|gpu}" >&2
	exit 1
fi

# Align with RHOAI wheels on packages.redhat.com (cp312 ubi9)
PY_VERSION="3.12"
case "$FLAVOR" in
cpu)
	RHOAI_INDEX_URL="https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.3/cpu-ubi9/simple/"
	;;
gpu)
	RHOAI_INDEX_URL="https://packages.redhat.com/api/pypi/public-rhai/rhoai/3.3/cuda12.9-ubi9/simple/"
	;;
esac

RAW_REQ_FILE="requirements.no_hashes.${FLAVOR}.txt"
SOURCE_FILE="requirements.source.${FLAVOR}.txt"
WHEEL_FILE="requirements.wheel.${FLAVOR}.txt"
SOURCE_HASH_FILE="requirements.hashes.source.${FLAVOR}.txt"
WHEEL_HASH_FILE="requirements.hashes.wheel.${FLAVOR}.txt"
BUILD_FILE="requirements-build.${FLAVOR}.txt"

# extra wheels for Cachi2 binary prefetch (build helpers + wheels that should not duplicate in build lockfile)
EXTRA_WHEELS="uv,uv-build,pip,maturin,griffe,griffecli,griffelib"
NO_WHEEL_PACKAGES="markupsafe"
# banks pulls in a circular build graph for pybuild-deps; match lightspeed-service.
# GPU: faiss-cpu resolves from PyPI; pybuild-deps cannot use its sdist graph (meson) in this hermetic flow.
SKIP_PYBUILD_PACKAGES="banks"
[[ "$FLAVOR" == "gpu" ]] && SKIP_PYBUILD_PACKAGES="banks,faiss-cpu"

# filtered source file for pybuild-deps to avoid RecursionError
SOURCE_FILE_FOR_BUILD=$(mktemp)

extract_pkg_name() {
	# e.g. "foo==1" -> foo; "foo @ https://..." -> foo
	local line="$1"
	local s="${line%%@*}"
	s="${s%%=*}"
	s="${s// /}"
	echo "$s" | tr '[:upper:]' '[:lower:]'
}

cleanup() {
	rm -f "$RAW_REQ_FILE" "$WHEEL_FILE" "$SOURCE_FILE" "$SOURCE_FILE_FOR_BUILD"
}
trap cleanup EXIT INT TERM

# --- 1) Compile unhashed, annotated with index origin (torch and other RHOAI wheels from the flavor index).
# Use first-index so RHOAI wins for shared names (e.g. torch); unsafe-best-match can pick PyPI torch and CUDA sdists.
# shellcheck disable=SC2206
uv pip compile pyproject.toml -o "$RAW_REQ_FILE" \
	--python-platform x86_64-unknown-linux-gnu \
	--python-version "$PY_VERSION" \
	--extra "$FLAVOR" \
	--refresh \
	--index "${RHOAI_INDEX_URL}" \
	--default-index https://pypi.org/simple/ \
	--index-strategy first-index \
	--emit-index-annotation \
	--no-sources \
	--override requirements.overrides.txt

echo "# Packages from pypi.org" >"$SOURCE_FILE"
echo "# This file was autogenerated by $(basename -- "$0")" >>"$SOURCE_FILE"
echo "# Packages from ${RHOAI_INDEX_URL}" >"$WHEEL_FILE"
echo "# This file was autogenerated by $(basename -- "$0")" >>"$WHEEL_FILE"
echo "--index-url ${RHOAI_INDEX_URL}" >>"$WHEEL_FILE"

# --- 2) Split by index origin (see lightspeed-service) + flush orphan top-level lines (e.g. URL pins)
current_package=""

while IFS= read -r line || [[ -n "$line" ]]; do
	if [[ "$line" =~ ^[a-zA-Z0-9] ]]; then
		if [[ -n "$current_package" ]]; then
			echo "$current_package" >>"$SOURCE_FILE"
		fi
		current_package="$line"
	elif [[ "$line" =~ ^[[:space:]]*#[[:space:]]*from[[:space:]]+(.*) ]]; then
		index_url="${BASH_REMATCH[1]}"
		if [[ -n "$current_package" ]]; then
			package_name="$(extract_pkg_name "$current_package")"
			force_no_wheel=0
			for no_wheel_pkg in ${NO_WHEEL_PACKAGES//,/ }; do
				[[ "$package_name" == "$no_wheel_pkg" ]] && force_no_wheel=1 && break
			done
			if [[ "$index_url" == "https://pypi.org/simple/" ]]; then
				echo "$current_package" >>"$SOURCE_FILE"
			elif [[ "$force_no_wheel" -eq 1 ]]; then
				echo "$current_package" >>"$SOURCE_FILE"
			elif [[ "$index_url" == "${RHOAI_INDEX_URL}" ]]; then
				echo "$current_package" >>"$WHEEL_FILE"
			else
				echo "$current_package" >>"$SOURCE_FILE"
			fi
			current_package=""
		fi
	fi
done <"$RAW_REQ_FILE"
if [[ -n "$current_package" ]]; then
	echo "$current_package" >>"$SOURCE_FILE"
fi

# uv can annotate these on PyPI; for Konflux (and pybuild-deps) prefer RHOAI wheels when that index carries them.
# faiss-cpu is forced to the wheel lock only for cpu: the cuda RHOAI index does not publish it (GPU resolves faiss from PyPI).
PKG_FORCE_WHEEL="numpy pandas scipy"
[[ "$FLAVOR" == "cpu" ]] && PKG_FORCE_WHEEL="faiss-cpu ${PKG_FORCE_WHEEL}"
for p in ${PKG_FORCE_WHEEL}; do
	tmpf=$(mktemp)
	while IFS= read -r pline; do
		case "$pline" in
		${p}==* | ${p}\ @\ *) echo "$pline" >>"$WHEEL_FILE" ;;
		*) echo "$pline" >>"$tmpf" ;;
		esac
	done <"$SOURCE_FILE"
	mv "$tmpf" "$SOURCE_FILE"
done

wheel_packages=$(grep -v "^[#-]" "$WHEEL_FILE" | sed 's/==.*//;s/[[:space:]]*@.*//' | awk 'NF' | tr '\n' ',' | sed 's/,$//')
echo "WHEEL_PACKAGE_NAMES: $wheel_packages" >&1

# --- 3) Hash lockfiles
# --universal and --python-platform are mutually exclusive in uv; RHOAI wheels are linux+cp311-specific here
uv pip compile "$WHEEL_FILE" --refresh --generate-hashes --index-url "${RHOAI_INDEX_URL}" \
	--python-version "$PY_VERSION" --python-platform x86_64-unknown-linux-gnu \
	--emit-index-url --no-deps --no-annotate >"$WHEEL_HASH_FILE"
uv pip compile "$SOURCE_FILE" --refresh --generate-hashes --python-version "$PY_VERSION" \
	--python-platform x86_64-unknown-linux-gnu \
	--emit-index-url --no-deps --no-annotate >"$SOURCE_HASH_FILE"

# --- 4) Drop extra wheels from source (they are only listed as binaries)
for pkg in ${EXTRA_WHEELS//,/ }; do
	pkg=$(echo "$pkg" | tr -d '[:space:]')
	[[ -n "$pkg" ]] && sed -i "/^${pkg}[=<>!~@]/d" "$SOURCE_FILE"
done

# Build deps: pybuild-deps, with optional banks → hatchling workaround
{
	grep -v "^[#-]" "$SOURCE_FILE" | while IFS= read -r bline; do
		[[ -z "$bline" ]] && continue
		pkg_name="${bline%%@*}"; pkg_name="${pkg_name%%=*}"; pkg_name="${pkg_name// /}"
		skip=0
		for skip_pkg in ${SKIP_PYBUILD_PACKAGES//,/ }; do
			skip_pkg=$(echo "$skip_pkg" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
			[[ -n "$skip_pkg" ]] && [[ $(echo "$pkg_name" | tr '[:upper:]' '[:lower:]') == "$skip_pkg" ]] && skip=1 && break
		done
		[[ $skip -eq 0 ]] && echo "$bline"
	done
	if [[ "$SKIP_PYBUILD_PACKAGES" == *"banks"* ]] && grep -qE '^banks' "$SOURCE_FILE" 2>/dev/null; then
		echo "hatchling==1.29.0"
	fi
} >>"$SOURCE_FILE_FOR_BUILD"

uv run --no-project --with "pybuild-deps>=0.5" pybuild-deps compile --output-file="$BUILD_FILE" "$SOURCE_FILE_FOR_BUILD"

# --- 5) Do not list wheel deps twice in build file
IFS=,
for pkg in $wheel_packages; do
	pkg=$(echo "$pkg" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
	[[ -z "$pkg" ]] && continue
	sed -i "/^${pkg}[=<>!~@]/d" "$BUILD_FILE" 2>/dev/null || true
done
unset IFS

# --- 6) Sync pip.binary.packages in prefetch-input (same sed as openshift/lightspeed-service).
# Requires a one-line JSON value containing "packages": "comma,separated,names".
for extra in ${EXTRA_WHEELS//,/ }; do
	extra=$(echo "$extra" | tr -d '[:space:]')
	[[ -n "$extra" ]] && wheel_packages="${wheel_packages:+$wheel_packages,}$extra"
done

update_prefetch_binary_packages() {
	local tf="$1"
	[[ -f "$tf" ]] || return 0
	if grep -q '"packages": "[^"]*"' "$tf"; then
		sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' "$tf"
		echo "  updated pip.binary.packages: $tf"
	else
		echo "  skip (no matching \"packages\" string): $tf" >&2
	fi
}

case "$FLAVOR" in
cpu)
	for tf in \
		.tekton/lightspeed-rag-tool-pull-request.yaml \
		.tekton/lightspeed-rag-tool-push.yaml \
		.konflux/lightspeed-rag-tool-pull-request.yaml \
		.konflux/lightspeed-rag-tool-push.yaml; do
		update_prefetch_binary_packages "$tf"
	done
	;;
gpu)
	for tf in \
		.tekton/own-app-lightspeed-rag-content-pull-request.yaml \
		.tekton/own-app-lightspeed-rag-content-push.yaml \
		.konflux/own-app-lightspeed-rag-content-pull-request.yaml \
		.konflux/own-app-lightspeed-rag-content-push.yaml; do
		update_prefetch_binary_packages "$tf"
	done
	;;
esac

echo "Done for flavor: $FLAVOR"
echo "  $SOURCE_HASH_FILE  ($(grep -c -v '^#' <"$SOURCE_HASH_FILE" 2>/dev/null || true) non-comment lines; hash lines vary)"
echo "  $WHEEL_HASH_FILE"
echo "  $BUILD_FILE"
echo "  pip.binary.packages value: $wheel_packages"
echo "Commit these, requirements.overrides*, and any updated PipelineRun YAML under .tekton/ and .konflux/"
